/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cv_FaceBeauty */

#ifndef _Included_com_cv_FaceBeauty
#define _Included_com_cv_FaceBeauty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cv_FaceBeauty
 * Method:    nativeFaceBeauty
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_cv_FaceBeauty_nativeFaceBeauty
  (JNIEnv *, jclass, jobject, jobject, jobject,
   jint, jint, jint,
   jint, jint,
   jboolean, jint, jint, jboolean simplified,
   jboolean mirror);

#ifdef __cplusplus
}
#endif
#endif
